export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";

export const ALL_COLLEGE_REQUEST = "ALL_COLLEGE_REQUEST";
export const ALL_COLLEGE_SUCCESS = "ALL_COLLEGE_SUCCESS";
export const ALL_COLLEGE_FAILURE = "ALL_COLLEGE_FAILURE";

export const COLLEGE_BRANCH_REQUEST = "COLLEGE_BRANCH_REQUEST";
export const COLLEGE_BRANCH_SUCCESS = "COLLEGE_BRANCH_SUCCESS";
export const COLLEGE_BRANCH_FAILURE = "COLLEGE_BRANCH_FAILURE";

export const COLLEGE_BRANCH_SEMESTER_REQUEST =
  "COLLEGE_BRANCH_SEMESTER_REQUEST";
export const COLLEGE_BRANCH_SEMESTER_SUCCESS =
  "COLLEGE_BRANCH_SEMESTER_SUCCESS";
export const COLLEGE_BRANCH_SEMESTER_FAILURE =
  "COLLEGE_BRANCH_SEMESTER_FAILURE";

export const SEMESTER_BRANCH_COURCES_REQUEST =
  "SEMESTER_BRANCH_COURCES_REQUEST";
export const SEMESTER_BRANCH_COURCES_SUCCESS =
  "SEMESTER_BRANCH_COURCES_SUCCESS";
export const SEMESTER_BRANCH_COURCES_FAILURE =
  "SEMESTER_BRANCH_COURCES_FAILURE";

export const SEMESTER_BRANCH_PAPERS_REQUEST = "SEMESTER_BRANCH_PAPERS_REQUEST";
export const SEMESTER_BRANCH_PAPERS_SUCCESS = "SEMESTER_BRANCH_PAPERS_SUCCESS";
export const SEMESTER_BRANCH_PAPERS_FAILURE = "SEMESTER_BRANCH_PAPERS_FAILURE";

export const SEMESTER_BRANCH_TT_REQUEST = "SEMESTER_BRANCH_TT_REQUEST";
export const SEMESTER_BRANCH_TT_SUCCESS = "SEMESTER_BRANCH_TT_SUCCESS";
export const SEMESTER_BRANCH_TT_FAILURE = "SEMESTER_BRANCH_TT_FAILURE";

export const CLEAR_ERROR = "CLEAR_ERROR";